# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fibonacci <- function(n) {
    .Call('RcppTutorialHelloRcpp_fibonacci', PACKAGE = 'RcppTutorialHelloRcpp', n)
}

hello <- function() {
    .Call('RcppTutorialHelloRcpp_hello', PACKAGE = 'RcppTutorialHelloRcpp')
}

rcpp_hello_world <- function() {
    .Call('RcppTutorialHelloRcpp_rcpp_hello_world', PACKAGE = 'RcppTutorialHelloRcpp')
}

timesTwo <- function(x) {
    .Call('RcppTutorialHelloRcpp_timesTwo', PACKAGE = 'RcppTutorialHelloRcpp', x)
}

